export const AvatarMenu = "AVATAR_MENU"
export const PasswordModal = "PASSWORD_MODAL"
export const FinancialYear = "FINANCIAL_YEAR"
export const FinancialYearModal = "FINANCIAL_YEAR_MODAL"
export const GeneralOffice = "GENERAL_OFFICE"
export const GeneralOfficeModal = "GENERAL_OFFICE_MODAL"
export const RecentMenus = "RECENT_MENUS"